server:
  port: 8080
#  servlet:
#    context-path: /hello
student:
  name: aaa
  age: 23
spring:
  mvc:
    view:
      prefix: /WEB_INF/views/
      suffix: .jsp
datasource:
  url: jdbc:sqlserver://192.168.50.128:1434;Database=SAMO
  username: sa
  password: admin@123
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
jpa:
  hibernate:
    ddl-auto: update