server:
  port: 8080
#  servlet:
#    context-path: /hello
student:
  name: aaa
  age: 23
spring:
  mvc:
    view:
      prefix: /WEB_INF/views/
      suffix: .jsp
  datasource:
    druid:
      dbfrom:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://192.168.1.251:1433;Database=SAMO
        username: sa
        password: admin@123
      dbto:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://192.168.1.251:1433;Database=SAMO
        username: sa
        password: admin@123
#  jpa:
#    hibernate:
#      ddl-auto: update